version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0-jdk
    steps:
      - checkout
      # Étapes de construction de l'application
      - run:
          name: Build and SonarQube analysis
          command: |
            mvn clean verify sonar:sonar \
              -Dsonar.projectKey=DemoCircleCi \
              -Dsonar.host.url=http://localhost:9000 \
              -Dsonar.login=sqp_3b1f7225aeb10a4460643e5e0d16296e1c76e522

workflows:
  version: 2
  deploy:
    jobs:
      - build
