version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11

    steps:
      - checkout

      - run:
          name: Set up SonarQube
          command: |
            #!/bin/bash -eo pipefail
            
            # Télécharge le Sonar Scanner CLI avec vérification de la réussite du téléchargement
            curl --location --silent --fail "https://somelinkto/download/sonar-scanner-cli.zip" -o sonar-scanner.zip || {
              echo "Erreur lors du téléchargement de Sonar Scanner CLI.";
              exit 1;
            }
            
            # Décompresse le fichier zip et vérifie si l'opération a réussi
            unzip -qq sonar-scanner.zip || {
              echo "Echec de la décompression de Sonar Scanner CLI.";
              exit 1;
            }
            
            # Ajoute le binaire Sonar Scanner au PATH
            export PATH=$PATH:$PWD/sonar-scanner/bin || {
              echo "Erreur lors de la configuration du PATH pour Sonar Scanner.";
              exit 1;
            }

      - run:
          name: Build and analyze
          command: |
            ./gradlew clean build
            sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=my-project-key

workflows:
  version: 2
  build-and-scan:
    jobs:
      - build
