version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11

    steps:
      - checkout

      - run:
          name: Set up SonarQube
          command: |
            curl --location --silent "https://somelinkto/download/sonar-scanner-cli.zip" -o sonar-scanner.zip
            unzip -qq sonar-scanner.zip
            export PATH=$PATH:$PWD/sonar-scanner/bin

      - run:
          name: Build and analyze
          command: |
            ./gradlew clean build
            sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=my-project-key

workflows:
  version: 2
  build-and-scan:
    jobs:
      - build
