version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0-jdk
    steps:
      - checkout
      # Étapes de construction de l'application
      - run:
          name: Build and SonarQube analysis
          command: |
           mvn clean verify sonar:sonar \
            -Dsonar.projectKey=DemoCircleCi \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=sqp_f44ad2e341dd6f97a4cd3670da650ae565c3c7cb

workflows:
  version: 2
  deploy:
    jobs:
      - build
