version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0-jdk
    steps:
      - checkout
      # Étapes de construction de l'application
      - run:
          name: Build and SonarQube analysis
          command: |
           mvn clean verify sonar:sonar \
            -Dsonar.projectKey=DemoCircleCi \
            -Dsonar.host.url=http://<SONARQUBE_IP>:9000 \
            -Dsonar.login=sqp_d4d285d9a43c94f770d08e1a263896fc0751f46c

workflows:
  version: 2
  deploy:
    jobs:
      - build
