version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    steps:
      - checkout

      - run: 
          name: Build project
          command: ./gradlew build

      - run:
          name: Run SonarQube analysis
          command: ./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2

  build_and_scan:
    jobs:
      - build:
          context: sonarqube-env
