jobs:
  deploy_test:
    steps:
      - run:
          name: Deploy to Test Environment
          command: |
            # Your deployment script or command for test environment

  deploy_staging:
    steps:
      - run:
          name: Deploy to Staging Environment
          command: |
            # Your deployment script or command for staging environment

  deploy_production:
    steps:
      - run:
          name: Deploy to Production Environment
          command: |
            # Your deployment script or command for production environment

workflows:
  version: 2
  main:
    jobs:
      - deploy_test
      - deploy_staging:
          requires:
            - deploy_test
      - deploy_production:
          requires:
            - deploy_staging
